QueryPath URI-Encoded
Before using the provided queryPath to construct the destination URL, we are URI-Encode it. For instance to avoid this kind of issues due to the whitespace:
java.lang.RuntimeException: java.net.URISyntaxException: Illegal character in path at index 79: http://opendatasalutedata.cloudapp.net/v1/datacatalog/ASLComuniPopolazione('3', '312')